name: Go

on:
  push:
    branches:
      - main
    paths:
      - '**.go'
  pull_request:
    branches:
      - main
    paths:
      - '**.go'
  workflow_dispatch: { }

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '^1.20'
          cache: true

      - name: Build
        run: make build

      - name: Test
        run: make test
